### ISSUE TITLE
Generar correus electronics aleatoris

### ISSUE THREAD

**Issue by NorbertAguilera** [lucasfer13/Projecte1#13]

**Comment by joan024** [comment]
public static void mail (String [] dades, String [] noms, String domini, String extensioDomini) {
	for(int i=0;i<dades.length;i++) {
		int index = (int)(noms.length * Math.random());
		dades[i]=noms[index]+"@"+extensioDomini+""+domini;
		System.out.println(dades[i]);
	}

**Comment by joan024** [comment]
public static void generarEmail(String [] dades, String [] noms, String domini, String extensioDomini, boolean semafor) {
	int index;
	domini = domini.toLowerCase();
	extensioDomini = extensioDomini.toLowerCase();
	if(semafor==true) {
		for(int i=0;i<dades.length;i++) {
		index = (int)(noms.length * Math.random());
		dades[i]=noms[index].toLowerCase()+"@"+domini+""+extensioDomini;
		}
	}
	else {
		for(int i=0;i<dades.length;i++) {
			dades[i]=noms[i].toLowerCase()+"@"+domini+""+extensioDomini;
		}
	}
}
