### ISSUE TITLE
Autoincrement

### ISSUE THREAD

**Issue by NorbertAguilera** [lucasfer13/Projecte1#17]

**Comment by NorbertAguilera** [comment]
//

**Comment by joan024** [comment]
package PrimeresProbes;

import java.util.Scanner;

public class Autonumeric {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner teclat = new Scanner(System.in);
		int inici=1, total=0;
		inici=teclat.nextInt();
		for(int i=0;i<200;i++) {
			total=inici+i;
			System.out.println(total);
		}
	}

}
