### ISSUE TITLE
IBAN Aleatori

### ISSUE THREAD

**Issue by NorbertAguilera** [lucasfer13/Projecte1#18]

**Comment by joan024** [comment]
package PrimeresProbes;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.Scanner;

public class IBAN {

	public static void main(String[] args) {
		Scanner teclat = new Scanner(System.in);
		String[] entitatBancaria = {"2080","1544","0241","0188","0182","0130","0234","9000","2105","0240","0487","0186","0238","3873","2038","0128","0138","0152","3842","3025","2100","2045","3035","3081","2000","1474","3821","3877","0239","2085","1465","2095","2048","0131","0108","2103"};
		String[] oficinaBancaria = {"5778","1809","5461","6828","3378","3380","6641","1454","2420","7675","8759","6759","3570","4610","3656","2465","0203","3554","1197","0148","3138","3051","0840","0870","0286","2699","2211","2850","4828","6308","3830"};
		System.out.println("Quants IBAN's vols?");int n=teclat.nextInt();
		for(int y=0; y<n; y++)
		{
			//CREACIÓ DE CONTABANCARIA:
			int[] contaBancaria = new int[10];
			for(int i=0; i<10;i++) {
				contaBancaria[i]=(int)(Math.random()*10+0);
			}
			//TROBAR NUMERO CONTROL:
			//PRIMER NUMERO
			//ENTITAT BANCARIA
			int indexEntitat = (int)(entitatBancaria.length*Math.random());
			int sumaA=0;
			for(int i=0;i<4;i++)
			{
				char numero = entitatBancaria[indexEntitat].charAt(i);
				int numeroActual = Character.getNumericValue(numero);
				if(i==0) {sumaA=sumaA+(numeroActual*4);} if(i==1) {sumaA=sumaA+(numeroActual*8);}
				if(i==2) {sumaA=sumaA+(numeroActual*5);} if(i==3) {sumaA=sumaA+(numeroActual*10);}
			}
			//OFICINA BANCARIA
			int indexOficina = (int)(oficinaBancaria.length*Math.random());
			int sumaB=0;
			for(int i=0;i<4;i++)
			{
				char numero = oficinaBancaria[indexOficina].charAt(i);
				int numeroActual = Character.getNumericValue(numero);
				if(i==0) {sumaB=sumaB+(numeroActual*9);} if(i==1) {sumaB=sumaB+(numeroActual*7);}
				if(i==2) {sumaB=sumaB+(numeroActual*3);} if(i==3) {sumaB=sumaB+(numeroActual*6);}
			}
			int restoC = 11-((sumaA+sumaB) % 11);
			if(restoC == 10) restoC = 1;
			else if (restoC == 11) restoC = 0;
			
			//SEGON NUMERO
			//CONTA BANCARIA
			int sumaD=0;
			for(int i=0;i<10;i++)
			{
				int numeroActual = contaBancaria[i];
				if(i==0) {sumaD=sumaD+(numeroActual*1);} if(i==1) {sumaD=sumaD+(numeroActual*2);}
				if(i==2) {sumaD=sumaD+(numeroActual*4);} if(i==3) {sumaD=sumaD+(numeroActual*8);}
				if(i==4) {sumaD=sumaD+(numeroActual*5);} if(i==5) {sumaD=sumaD+(numeroActual*10);}
				if(i==6) {sumaD=sumaD+(numeroActual*9);} if(i==7) {sumaD=sumaD+(numeroActual*7);}
				if(i==8) {sumaD=sumaD+(numeroActual*3);} if(i==9) {sumaD=sumaD+(numeroActual*6);}
			}
			int restoE = 11-(sumaD % 11);
			if(restoE == 10) restoE = 1;
			else if (restoE == 11) restoE = 0;
			//TROBAR NUMERO ES	
			BigInteger numeroComplet = new BigInteger (entitatBancaria[indexEntitat]+""+oficinaBancaria[indexOficina]+""+restoC+""+restoE+""+contaBancaria[0]+""+contaBancaria[1]+""+contaBancaria[2]+""+contaBancaria[3]+""+contaBancaria[4]+""+contaBancaria[5]+""+contaBancaria[6]+""+contaBancaria[7]+""+contaBancaria[8]+""+contaBancaria[9]+""+142800);
			BigInteger modul = new BigInteger(""+97);
			int numeroES = numeroComplet.mod(modul).intValue();
			int total = 98 - numeroES;
			//MOSTRAR IBAN
			BigInteger numeroComplet2 = new BigInteger (entitatBancaria[indexEntitat]+""+oficinaBancaria[indexOficina]+""+restoC+""+restoE+""+contaBancaria[0]+""+contaBancaria[1]+""+contaBancaria[2]+""+contaBancaria[3]+""+contaBancaria[4]+""+contaBancaria[5]+""+contaBancaria[6]+""+contaBancaria[7]+""+contaBancaria[8]+""+contaBancaria[9]);
			if(total<=9) {
				if(entitatBancaria[indexEntitat].charAt(0)=='0') System.out.println("ES"+"0"+total+"0"+numeroComplet2);
				else System.out.println("ES"+"0"+total+numeroComplet2);
			}
			else {	
				if(entitatBancaria[indexEntitat].charAt(0)=='0') System.out.println("ES"+total+"0"+numeroComplet2);	
				else System.out.println("ES"+total+numeroComplet2);
			}
		}	
			
	}

}
