### ISSUE TITLE
Generar Contrasenya aleatoria

### ISSUE THREAD

**Issue by NorbertAguilera** [lucasfer13/Projecte1#19]

**Comment by lucasfer13** [comment]
public static void generarPassword(String dades[], int longitud, int lletres, int majuscules, int minuscules, int numeros, int simbols, Random aleatori, int numRegistres) {
String simbol= "@#:;.,?\"/()\\|-_}{^*!%=~, <>+";
String numbers="0123456789";
int tipusCaracter, ascii, i, i2, cmajuscules = majuscules, clletres = lletres, cminuscules = minuscules, csimbols = simbols, cnumeros = numeros;
char caracter = 0;
String password;

for(i2=0;i2<numRegistres;i2++) {
password = "";
majuscules = cmajuscules;
numeros = cnumeros;
lletres = clletres;
minuscules = cminuscules;
simbols = csimbols;
for(i=0;i<longitud;i++) {
tipusCaracter = aleatori.nextInt(4)+1;
switch (tipusCaracter) {
	case 1:
		if (minuscules > 0 || (majuscules <= 0 && simbols <= 0 && numeros <= 0)) {
			ascii = aleatori.nextInt(122-97)+97;
			caracter = (char) ascii;
			minuscules--;	
			lletres--;
		} else {
			caracter = 0;
			i--;
		}
		break;
	case 2:
		if (majuscules > 0 || (minuscules<=0 && simbols<=0 && numeros <= 0)) {
			ascii = aleatori.nextInt(90-65)+65;
			caracter = (char) ascii;
			majuscules--;
			lletres--;
		} else {
			caracter = 0;
			i--;
		}
		break;
	case 3:
		if (simbols>0 || (minuscules<=0 && majuscules<=0 && lletres <=0 && numeros <= 0)) {
			ascii = aleatori.nextInt(simbol.length());
			caracter = simbol.charAt(ascii);
			simbols--;
		} else {
			caracter = 0;
			i--;
		}
		break;
	case 4:
		if (numeros>0 || (minuscules<=0 && majuscules<=0 && lletres <=0 && simbols <= 0)) {
			ascii = aleatori.nextInt(10);
			caracter = numbers.charAt(ascii);
			numeros--;
		} else {
			caracter = 0;
			i--;
		}
		break;
}
if (caracter != 0) {
	password=password+caracter+"";
}
}
dades[i2] = password;
}
}
