### ISSUE TITLE
omplir array amb dades aleatories especificades en un arxiu d'entrada

### ISSUE THREAD

**Issue by lucasfer13** [lucasfer13/Projecte1#26]

**Comment by NorbertAguilera** [comment]
//ficar a la memoria
public class llegirFitxers {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		String nom;
		String [] fit=new String [200];
		//String [] barrejats=new String [200];
		try {

			File fitxer=new File("C:\\Users\\naca6\\OneDrive\\Escritorio\\dam2\\Ptojecte2\\Noms.csv");
			FileReader fr = new FileReader(fitxer);
			BufferedReader br = new BufferedReader(fr);
			int i=0;
		while(i<200) {
			fit[i] = br.readLine();
			
			//System.out.println(nom);
			i++;
		}
		br.close();
		fr.close();
		fr = new FileReader(fitxer);
		 br = new BufferedReader(fr);
		
		} catch (Exception pasanCosas) {
			pasanCosas.printStackTrace();
		}
		List<String> list =Arrays.asList(fit);
		Collections.shuffle(list);
		for(int i=0;i<200;i++) {
			System.out.println(fit[i]);
		}
	}

}

**Comment by NorbertAguilera** [comment]
public static void main(String[] args) {
		// TODO Auto-generated method stub
		
			
			String nom;
			//String [] barrejats=new String [200];
			try {
				String nom1[]=new String[200],cognom[]=new String[200],Adreqes[]=new String[200],Estudis[]=new String[200],Pais[]=new String[200],Ciutats[]=new String[200],Url[]=new String[200],Treballs[]=new String[200],Empreses[]=new String[200];
				String colors[]=new String[200];
				boolean agafaCol=true;
				File fitxer=new File("C:\\Users\\naca6\\OneDrive\\Escritorio\\dam2\\Ptojecte2\\totJunt .csv");
				FileReader fr = new FileReader(fitxer);
				String separa []=new String[10];
				BufferedReader br = new BufferedReader(fr);
				int lin=200;
				int i=0;
				String [] fit=new String [lin];
			while(i<lin) {
				fit[i] = br.readLine();
				separa=fit[i].split(",");
				nom1[i]=separa[0];
				cognom[i]=separa[1];
				Adreqes[i]=separa[2];//4
				Estudis[i]=separa[3];
				Pais[i]=separa[4];//6
				Ciutats[i]=separa[5];//3
				Url[i]=separa[6];
				Treballs[i]=separa[7];//5
				Empreses[i]=separa[8];
				/*if(separa[9].equals("zzz")) {
					agafaCol=false;
				}
				if(agafaCol==true){
					//colors[i]=separa[8];
				}*/
				i++;
			}
			br.close();
			fr.close();
			fr = new FileReader(fitxer);
			 br = new BufferedReader(fr);
			 List<String> list =Arrays.asList(fit);
			Collections.shuffle(list);
			List<String> SN =Arrays.asList(nom1);
			Collections.shuffle(SN);
			List<String> SC =Arrays.asList(cognom);
			Collections.shuffle(SC);
			List<String> SA =Arrays.asList(Adreqes);
			Collections.shuffle(SA);
			List<String> SE =Arrays.asList(Adreqes);
			Collections.shuffle(SE);
			List<String> SP =Arrays.asList(Pais);
			Collections.shuffle(SP);
			List<String> SCi =Arrays.asList(Ciutats);
			Collections.shuffle(SCi);
			List<String> SU =Arrays.asList(Url);
			Collections.shuffle(SU);
			List<String> ST =Arrays.asList(Treballs);
			Collections.shuffle(ST);
			List<String> SEm =Arrays.asList(Empreses);
			Collections.shuffle(SEm);
			
			for(int a=0;a<lin;a++) {
				System.out.println(nom1[a]);
				System.out.println(cognom[a]);
				System.out.println(Adreqes[a]);
				System.out.println(Estudis[a]);
				System.out.println(Pais[a]);
				System.out.println(Ciutats[a]);
				System.out.println(Url[a]);
				System.out.println(Treballs[a]);
				System.out.println(Empreses[a]);
				
				System.out.println("___________________________________________________");
				
				
			}
			
			} catch (Exception pasanCosas) {
				pasanCosas.printStackTrace();
			}		
	}

}

**Comment by NorbertAguilera** [comment]
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class llegeixProva {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			boolean agafaCol=true;
			File fitxer=new File("C:\\Users\\naca6\\OneDrive\\Escritorio\\dam2\\Ptojecte2\\totJunt .csv");
			FileReader fr = new FileReader(fitxer);
			String separa []=new String[10];
			BufferedReader br = new BufferedReader(fr);
			int i =0,z=0,a=0;
			String llegit[][]=new String[10][200];
			String fit;
			while(i<200) {
				while(i<200) {
					fit = br.readLine();
					separa=fit.split(",");
					//System.out.println(separa[9]);
					for(z=0;z<9;z++) {
						if(z<9) {
							llegit[z][i]=separa[z];
						}else if(z==9) {
							if(separa[9].equals("zzz")) {
								agafaCol=false;
							}else if(agafaCol==true) {
								llegit[9][i]=separa[9];
							}else {
								llegit[9][i]=llegit[9][a];
							}
							
						}
					
					}
					i++;
				}
				for(z=0;z<9;z++) {
					List<String> barr =Arrays.asList(llegit[z]);
					Collections.shuffle(barr);
				}
				for(i=0;i<200;i++) {
					for(z=0;z<10;z++) {
						System.out.println(llegit[z][i]);
					}
					System.out.println("_____________________________________________");
				}
			}
		} catch (Exception pasanCosas) {
			pasanCosas.printStackTrace();
		}
	}

}
