### ISSUE TITLE
Generar un XML de prova

### ISSUE THREAD

**Issue by lucasfer13** [lucasfer13/Projecte1#30]
Pes: 5h

**Comment by NorbertAguilera** [comment]
public static void passaXml (int numRegistres,int numLinies,String dadesAleatories[][],String camps[][] ) throws FileNotFoundException {
	// TODO Auto-generated method stub
	PrintStream escriuXML =new PrintStream (new File("dades.xml"));
	camps = new String[numLinies][8];
	dadesAleatories=new String [numLinies][numRegistres];
	int a;
	escriuXML.println("<xml>");
	escriuXML.println("	<camp>");
	for(int i=0;i<numRegistres;i++) {
		
		escriuXML.println("		<dades>");
		for(a=0;a<numLinies;a++) {
			escriuXML.println("			<"+camps[a][0]+">"+dadesAleatories[a][i]+"</"+camps[a][0]+">");
		}
		escriuXML.println("		</dades>");
		
	}
	escriuXML.println("	</camp>");
	escriuXML.println("</xml>");
}

**Comment by NorbertAguilera** [comment]
public static void passaXml (int numRegistres,int numLinies,String dadesAleatories[][],String camps[][] ) throws FileNotFoundException {
		// TODO Auto-generated method stub
		PrintStream escriuXML =new PrintStream (new File("dades.xml"));
		/*camps = new String[numLinies][8];
		dadesAleatories=new String [numLinies][numRegistres];*/
		int a;
		escriuXML.println("<?xml-stylesheet type=\\\"text/xls\\\" href=\\\"xslt.xsl\\\"?>");//
		escriuXML.println("	<camp>");
		for(int i=0;i<numRegistres;i++) {

			escriuXML.println("		<dades>");
			for(a=0;a<numLinies;a++) {
				escriuXML.println("			<"+camps[a][0]+">"+dadesAleatories[a][i]+"</"+camps[a][0]+">");
			}
			escriuXML.println("		</dades>");
			
		}
		escriuXML.println("	</camp>");
		escriuXML.println("</xml>");

		}
