### ISSUE TITLE
Generar XSD de prova

### ISSUE THREAD

**Issue by lucasfer13** [lucasfer13/Projecte1#34]
Pes: 5h

**Comment by joan024** [comment]
public static void generarXsd(String[][] camps , File sortida) {
		File sortidaXsd = new File (sortida.getParent()+"\\xsd.xsd");
		try {
			PrintStream out = new PrintStream(sortidaXsd);
			out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
			out.println("<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\">");
			out.println("\t<xs:element name=\"provaXSD\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			out.println("\t\t\t\t<xs:element ref=\"record\" maxOccurs=\"unbounded\"/>");
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("\t<xs:element name=\"record\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			for(int i=0;i<camps.length;i++) {
				out.println("\t\t\t\t<xs:element name= "+camps[i]+" type=\"xs:string\"/>");
				
				//out.println("<xs:element name=\"id\" type=\"xs:string\"/>");
			}
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("</xs:schema>");
					
			
		} catch (Exception ex) {
			System.out.println(ex);
		}
	
	}
	}
