### ISSUE TITLE
Funció per generar XSD

### ISSUE THREAD

**Issue by lucasfer13** [lucasfer13/Projecte1#37]
Pes: 10h

**Comment by joan024** [comment]
public static void generarXsd(String[][] camps , File sortida) {
		File sortidaXsd = new File (sortida.getParent()+"\\xsd.xsd");
		try {
			PrintStream out = new PrintStream(sortidaXsd);
			out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
			out.println("<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\">");
			out.println("\t<xs:element name=\"camp\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			out.println("\t\t\t\t<xs:element ref=\"dades\" maxOccurs=\"unbounded\"/>");
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("\t<xs:element name=\"dades\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			for(int i=0;i<camps.length;i++) {
				if(camps[i][1].equals("11")) { //BOOLEAN
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:boolean\"/>");
				}
				if(camps[i][1].equals("12")) { //NUMBER
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:decimal\" xs:minInclusive value=\"0\" xs:maxInclusive value=\"1000\"/>");
				}
				if(camps[i][1].equals("15")) { //PASSWORD
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\" xs:length value="+camps[i][7]+"/>");
				}
				if(camps[i][1].equals("16")) { //DATES
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\"/>");
				}
				if(camps[i][1].equals("17")) { //IBAN
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\" xs:pattern value=\"[E][S][0-9]{22}\"/>");
				}
				if(camps[i][1].equals("18")) { //DNI
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\" xs:pattern value=\"[0-9]{8}[A-Z]{1}\"/>");
				}
				if(camps[i][1].equals("19")) { //AUTONUMÈRIC
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:positiveInteger\" default=\"1\"/>");
				}
				else { //LA RESTA DE CAMPS
				out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\"/>");
				}
			}
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("</xs:schema>");
					
			
		} catch (Exception ex) {
			System.out.println(ex);
		}
	
	}

**Comment by joan024** [comment]
public static void generarXsd(String[][] camps , File sortida) {
		File sortidaXsd = new File (sortida.getParent()+"\\xsd.xsd");
		try {
			PrintStream out = new PrintStream(sortidaXsd);
			out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
			out.println("<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\">");
			out.println("\t<xs:element name=\"camp\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			out.println("\t\t\t\t<xs:element ref=\"dades\" maxOccurs=\"unbounded\"/>");
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("\t<xs:element name=\"dades\">");
			out.println("\t\t<xs:complexType>");
			out.println("\t\t\t<xs:sequence>");
			for(int i=0;i<camps.length;i++) {
				if(camps[i][1].equals("11")) { //BOOLEAN
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\" type=\"xs:boolean\"/>");
				}
				else if(camps[i][1].equals("12")) { //NUMBER
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\">");
					out.println("\t\t\t\t\t<xs:simpleType>");
					out.println("\t\t\t\t\t\t<xs:restriction base=\"xs:decimal\">");
					out.println("\t\t\t\t\t\t\t<xs:minInclusive value=\"0\"/>");
					out.println("\t\t\t\t\t\t\t<xs:maxInclusive value=\"1000\"/>");
					out.println("\t\t\t\t\t\t</xs:restriction>");
					out.println("\t\t\t\t\t</xs:simpleType>");
					out.println("\t\t\t\t</xs:element>");
				}
				else if(camps[i][1].equals("15")) { //PASSWORD
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\">");
					out.println("\t\t\t\t\t<xs:simpleType>");
					out.println("\t\t\t\t\t\t<xs:restriction base=\"xs:string\">");
					out.println("\t\t\t\t\t\t\t<xs:length value=\""+camps[i][7]+"\"/>");
					out.println("\t\t\t\t\t\t</xs:restriction>");
					out.println("\t\t\t\t\t</xs:simpleType>");
					out.println("\t\t\t\t</xs:element>");
				}
				else if(camps[i][1].equals("16")) { //DATES
					out.println("\t\t\t\t<xs:element name= "+camps[i][0]+" type=\"xs:string\"/>");
				}
				else if(camps[i][1].equals("17")) { //IBAN
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\">");
					out.println("\t\t\t\t\t<xs:simpleType>");
					out.println("\t\t\t\t\t\t<xs:restriction base=\"xs:string\">");
					out.println("\t\t\t\t\t\t\t<xs:pattern value=\"[E][S][0-9]{22}\"/>");
					out.println("\t\t\t\t\t\t</xs:restriction>");
					out.println("\t\t\t\t\t</xs:simpleType>");
					out.println("\t\t\t\t</xs:element>");
				}
				else if(camps[i][1].equals("18")) { //DNI
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\">");
					out.println("\t\t\t\t\t<xs:simpleType>");
					out.println("\t\t\t\t\t\t<xs:restriction base=\"xs:string\">");
					out.println("\t\t\t\t\t\t\t<xs:pattern value=\"[0-9]{8}[A-Z]{1}\"/>");
					out.println("\t\t\t\t\t\t</xs:restriction>");
					out.println("\t\t\t\t\t</xs:simpleType>");
					out.println("\t\t\t\t</xs:element>");
				}
				else if(camps[i][1].equals("19")) { //AUTONUMÈRIC
					out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\" type=\"xs:positiveInteger\" default=\"1\"/>");
				}
				else { //LA RESTA DE CAMPS
				out.println("\t\t\t\t<xs:element name=\""+camps[i][0]+"\" type=\"xs:string\"/>");
				}
			}
			out.println("\t\t\t</xs:sequence>");
			out.println("\t\t</xs:complexType>");
			out.println("\t</xs:element>");
			out.println("</xs:schema>");
					
			
		} catch (Exception ex) {
			System.out.println(ex);
		}
	
	}
	}
