### ISSUE TITLE
Fer una preview abans de generar l'arxiu de sortida

### ISSUE THREAD

**Issue by joan024** [lucasfer13/Projecte1#78]
Pes: 5h

**Comment by NorbertAguilera** [comment]
mostraPre(dadesAleatories,camps);
				
				if(despresDePre(dadesAleatories,camps)==1)
				{
					if (formatSortida.equals("XML")) {
						sortida = new File(sortida.getAbsolutePath()+"\\dades.xml");
						try {
							if (!sortida.exists()) {
								sortida.createNewFile();
							}
							sortidaXML(dadesAleatories, camps, sortida);
						} catch (FileNotFoundException e) {
							e.printStackTrace();
						} catch (IOException e) {
							e.printStackTrace();
						}
						generarXSLT(camps, sortida);
						generarXSD(camps, sortida);
						System.out.println("Generat arxiu XML.");
					} else if (formatSortida.equals("SQL")) {
						sortida = new File(sortida.getAbsolutePath()+"\\dades.sql");
						if (!sortida.exists()) {
							try {
								sortida.createNewFile();
							} catch (IOException e) {
								e.printStackTrace();
							}
						}
						generarSQL(camps, dadesAleatories, sortida);
						System.out.println("Generat arxiu SQL.");
					} else if (formatSortida.equals("CSV")) {
						sortida = new File(sortida.getAbsolutePath()+"\\dades.csv");
						if (!sortida.exists()) {
							try {
								sortida.createNewFile();
							} catch (IOException e) {
								e.printStackTrace();
							}
						}
						generarCSV(dadesAleatories, camps, sortida);
					} else if (formatSortida.equals("JSON")) {
						sortida = new File(sortida.getAbsolutePath()+"\\dades.json");
						if (!sortida.exists()) {
							try {
								sortida.createNewFile();
							} catch (IOException e) {
								e.printStackTrace();
							}
						}
						generarJSON(dadesAleatories, camps, sortida);
					}
				}else if(despresDePre(dadesAleatories,camps)==2) {
					main(args);
				}else{
					end = true;
				}

**Comment by NorbertAguilera** [comment]
//funció per a mostrar una taula amb totes les dades aleatories a ver com es veuria
	public static void mostraPre(String dadesAleatories[][],String camps[][]) {
		DefaultTableModel model = new DefaultTableModel();
		for(int i=0;i<camps.length;i++) {
			model.addColumn(camps[i][0]);
		}
		String dades[]=new String[dadesAleatories.length] ;
		for(int a=0;a<dadesAleatories[0].length;a++) {
			for(int i=0;i<camps.length;i++) {
				dades[i]=dadesAleatories[i][a];
			}
			model.addRow(ficarFiles(dades));			
		}
		JTable taula = new JTable(model);
		taula.setBounds(30,40,200,300);          
	    JScrollPane sp=new JScrollPane(taula); 
	    JFrame f = new JFrame();
	    f.add(sp);          
	    f.setSize(3000,4000);    
	    f.setVisible(true);	
	    
	}
	//funció per a crear les files per a la taula 
	public static Object[] ficarFiles(String dades[]) {
		Object n[]=new Object[dades.length];
			for(int a = 0; a < dades.length; a++) {
				n[a]=dades[a];
			}
		return n;
	}
	//menú per a la previsualització
	public static int despresDePre(String dadesAleatories[][],String camps[][]) {
		String opcioS="";int opcio=-1;
		boolean opcioValida=false;
		Scanner teclat=new Scanner(System.in);
		System.out.println("Que vols fer ara?");
		System.out.println("0. Sortir");
		System.out.println("1. Generar amb aquestes dades");
		System.out.println("2. Canviar la ruta del fitxer d'entrada.");
		opcioS=teclat.next();
		if (opcioS.length() == 1 && Character.isDigit(opcioS.charAt(0))) {//validem la pocio triada
			opcio = Integer.parseInt(opcioS);
			if (opcio >= 1 || opcio <= 2 || opcio <= 3) {
				opcioValida = true;
			}
			if(opcio>2||opcio<0) {
				System.out.println("Opció no valida");
				despresDePre(dadesAleatories, camps);
			}
		}
		if(!opcioValida) {//si no es valida utilitzem recursivitat
			System.out.println("Opció no valida");
			despresDePre(dadesAleatories, camps);
		}else {
			return opcio;
		}
		return opcio;
	}
