### ISSUE TITLE
Generació IP

### ISSUE THREAD

**Issue by lucasfer13** [lucasfer13/Projecte1#8]
Pes: 2H

**Comment by NorbertAguilera** [comment]
//Documentar memoria
public class IPAleatoria {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random num=new Random();
		int primer,segon,tercer,cuart;
		String ipValida [] =new String [200];
		String ip;
		
		for(int i=0;i<200;i++) 
		{
			primer=1+num.nextInt(254);
			segon=1+num.nextInt(254);
			tercer=1+num.nextInt(254);
			cuart=1+num.nextInt(254);
			ipValida[i]=primer+"."+segon+"."+tercer+"."+cuart;
			System.out.println(ipValida[i]);
		}
		
		
	}

}
